# Generated by Django 4.1.3 on 2023-03-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queries", "0002_rename_student_teacher_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.CharField(max_length=10)),
                ("emp_fname", models.CharField(max_length=10)),
                ("emp_lname", models.CharField(max_length=13)),
                ("emp_dept", models.CharField(max_length=20)),
                ("emp_city", models.CharField(max_length=20)),
            ],
        ),
    ]
